# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import image

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 10, 141, 131))
        self.label_5.setStyleSheet("image: url(:/myimg/logo.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 210, 131, 91))
        self.label_2.setStyleSheet("image: url(:/myimg/dentat.jpg);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(370, 210, 91, 91))
        self.label_3.setStyleSheet("image: url(:/myimg/dentat.jpg);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(620, 210, 121, 91))
        self.label_4.setStyleSheet("image: url(:/myimg/dentat.jpg);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 40, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_on1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_on1.setGeometry(QtCore.QRect(30, 330, 93, 28))
        self.btn_on1.setObjectName("btn_on1")
        self.btn_off1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_off1.setGeometry(QtCore.QRect(160, 330, 93, 28))
        self.btn_off1.setObjectName("btn_off1")
        self.btn_on1_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_on1_2.setGeometry(QtCore.QRect(310, 330, 93, 28))
        self.btn_on1_2.setObjectName("btn_on1_2")
        self.btn_off1_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_off1_2.setGeometry(QtCore.QRect(430, 330, 93, 28))
        self.btn_off1_2.setObjectName("btn_off1_2")
        self.btn_on1_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_on1_3.setGeometry(QtCore.QRect(570, 330, 93, 28))
        self.btn_on1_3.setObjectName("btn_on1_3")
        self.btn_off1_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_off1_3.setGeometry(QtCore.QRect(690, 330, 93, 28))
        self.btn_off1_3.setObjectName("btn_off1_3")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(80, 490, 651, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(80, 510, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(630, 500, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.btn_all = QtWidgets.QPushButton(self.centralwidget)
        self.btn_all.setGeometry(QtCore.QRect(80, 430, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_all.setFont(font)
        self.btn_all.setObjectName("btn_all")
        self.btn_ext = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ext.setGeometry(QtCore.QRect(570, 430, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_ext.setFont(font)
        self.btn_ext.setObjectName("btn_ext")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.btn_on1.clicked.connect(self.on_1)
        self.btn_off1.clicked.connect(self.off_1)
        self.btn_on1_2.clicked.connect(self.on_2)
        self.btn_off1_2.clicked.connect(self.off_2)
        self.btn_on1_3.clicked.connect(self.on_3)
        self.btn_off1_3.clicked.connect(self.off_3)
        self.btn_all.clicked.connect(self.on_all)
        self.btn_ext.clicked.connect(sys.exit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "IOT BẬT TẮT ĐÈN"))
        self.btn_on1.setText(_translate("MainWindow", "ON"))
        self.btn_off1.setText(_translate("MainWindow", "OFF"))
        self.btn_on1_2.setText(_translate("MainWindow", "ON"))
        self.btn_off1_2.setText(_translate("MainWindow", "OFF"))
        self.btn_on1_3.setText(_translate("MainWindow", "ON"))
        self.btn_off1_3.setText(_translate("MainWindow", "OFF"))
        self.label_8.setText(_translate("MainWindow", "Cao Gia Nghi"))
        self.label_9.setText(_translate("MainWindow", "19161140"))
        self.btn_all.setText(_translate("MainWindow", "BẬT TẤT CẢ ĐÈN"))
        self.btn_ext.setText(_translate("MainWindow", "EXIT"))

    def on_1(self):
        self.label_2.setStyleSheet("image: url(:/myimg/densang);")
    def off_1(self):
        self.label_2.setStyleSheet("image: url(:/myimg/dentat);")
    def on_2(self):
        self.label_3.setStyleSheet("image: url(:/myimg/densang);")
    def off_2(self):
        self.label_3.setStyleSheet("image: url(:/myimg/dentat);")
    def on_3(self):
        self.label_4.setStyleSheet("image: url(:/myimg/densang);")
    def off_3(self):
        self.label_4.setStyleSheet("image: url(:/myimg/dentat);")
    def on_all(self):
        self.label_2.setStyleSheet("image: url(:/myimg/densang);")
        self.label_3.setStyleSheet("image: url(:/myimg/densang);")
        self.label_4.setStyleSheet("image: url(:/myimg/densang);")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
